---
version: "3"

services:
    clickhouse-server:
        image: clickhouse/clickhouse-server:22.1.3.7
        hostname: clickhouse-server
        container_name: clickhouse-server
        ports:
            - "9000:9000"
        networks:
            - ch-net
        volumes:
            - ${PWD}/tests/config/admin.xml:/etc/clickhouse-server/users.d/admin.xml

networks:
    ch-net:
